name: 'Setup tox'
description: 'Install tox and restore cache'
inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax."
    required: false
    default: '3.x'

runs:
  using: 'composite'
  steps:
    - name: Disable PDM update check
      run: echo "PDM_CHECK_UPDATE=False" >> $GITHUB_ENV
      shell: bash
    - uses: pdm-project/setup-pdm@v4
      with:
        version: '2.14.0'
        python-version: ${{ inputs.python-version }}
        ### setup-pdm cache seems broken. See https://github.com/pdm-project/setup-pdm/issues/43
        # cache: true
        # cache-dependency-path: './pdm.lock'
    - name: Install dependencies
      ### This command fails at least 1 in 100 times on Windows
      # run: pdm sync --global --project=. --no-self --dev --group=tox
      run: |
        pdm export --dev --group tox --format requirements --without-hashes --output requirements-tox.txt
        pip install -r requirements-tox.txt
      env:
        PDM_USE_VENV: False
      shell: bash
    - name: Disable tox parallel spinner by default
      run: echo "TOX_PARALLEL_NO_SPINNER=1" >> $GITHUB_ENV
      shell: bash
