name: 'Setup tox'
description: 'Install tox and restore cache'
inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax."
    required: false
    default: '3.x'

runs:
  using: 'composite'
  steps:
    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ inputs.python-version }}
        cache: true
        cache-dependency-path: './pdm.lock'
    - name: Disable PDM update check
      run: echo "PDM_CHECK_UPDATE=False" >> $GITHUB_ENV
      shell: bash
    - name: Install dependencies
      run: pdm sync --global --project=. --no-self --dev --group=tox
      shell: bash
    - name: Disable tox parallel spinner by default
      run: echo "TOX_PARALLEL_NO_SPINNER=1" >> $GITHUB_ENV
      shell: bash
