name: 'Setup tox'
description: 'Install tox and restore cache'
inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax."
    required: false
    default: '3.x'

runs:
  using: 'composite'
  steps:
    - name: Disable PDM update check
      run: echo "PDM_CHECK_UPDATE=False" >> $GITHUB_ENV
      shell: bash
    - name: Create cache key from workflow
      run: echo "Runner=${{ runner.os }}-${{ runner.arch }}; Workflow=${{ github.workflow }}" > .github/.workflow.cache.key
      shell: bash
    # Use a pinned commit to use the new feature added (and which is not currently added to v4)
    # c.f. https://github.com/pdm-project/setup-pdm/pull/60
    - uses: pdm-project/setup-pdm@2f3a9be7ac56a6e5c1ea605f8e9d0f0500363705  # v4
      with:
        version: '2.19.3'
        python-version: ${{ inputs.python-version }}
        cache: true
        cache-restore-exact-match: true
        cache-dependency-path: |
          ./pdm.lock
          .github/.workflow.cache.key
    - name: Install dependencies
      ### This command fails at least 1 in 100 times on Windows
      # run: pdm sync --global --project=. --no-self --dev --group=tox
      run: |
        pdm export --no-default --dev --group tox --format requirements --without-hashes --output requirements-tox.txt
        pip install -r requirements-tox.txt
        rm -f requirements-tox.txt
      env:
        PDM_USE_VENV: False
      shell: bash
    - name: Disable tox parallel spinner by default
      run: echo "TOX_PARALLEL_NO_SPINNER=1" >> $GITHUB_ENV
      shell: bash
