comment:
  require_changes: false  # Always show messages if codecov is triggered
  layout: "flags"  # Only show coverage by flags
  # unit and functional tests run:
  # Python 3.11: Linux, Windows, MacOS, FreeBSD, OpenBSD, NetBSD.
  # Python 3.12: Linux, Windows, MacOS.
  # Python 3.13: Linux, Windows, MacOS.
  # Final calculation:
  # (nb_builds_per_python_version(==6 + 3 + 3) * (nb_test_runs (unit + functional) (==2))
  after_n_builds: 24
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
github_checks:
  annotations: false  # Codecov may pollute the "files" diff view
