changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - pre-commit-ci  # autoupdate PRs: Only affects development
      - dependabot  # dependabot is configured to check github actions' pinned version in workflows
  categories:
    - title: Breaking changes
      labels:
        - breaking-changes
    - title: Bug fixes
      labels:
        - bug
    - title: Features/Improvement
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
      exclude:
        labels:
          - integration
          - development-process
    - title: Dependencies
      labels:
        - dependencies
      exclude:
        labels:
          - integration
    - title: Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - development-process
