exclude_dirs: [
  'benchmark_server',
  'micro_benchmarks',
  'tests'
]
skips: [
  'B403',  # Imports of "pickle"
  'B610',  # This project does not use Django :)
]

assert_used:
  skips: ['docs/**/*.py']
