[tool.bumpversion]
current_version = "1.1.4"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(?:(?P<release>rc)(?P<serial>\d+))?'
serialize = [
	"{major}.{minor}.{patch}{release}{serial}",
	"{major}.{minor}.{patch}",
]
message = "Bump version: {current_version} -> {new_version}"
tag_name = "{new_version}"

[tool.bumpversion.parts.release]
first_value = "rc"
optional_value = "final"
values = [
	"rc",
	"final",
]

[tool.bumpversion.parts.serial]
first_value = 1

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'fallback-version = "{current_version}"'
replace = 'fallback-version = "{new_version}"'
