version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install --no-cache-dir pdm==2.22.2
      - pdm config check_update false
      - pdm use -f $READTHEDOCS_VIRTUALENV_PATH
    post_install:
      - pdm sync --dev --group=doc

sphinx:
  configuration: docs/source/conf.py
