version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install --no-cache-dir pdm==2.9.2
      - pdm config python.use_venv false
      - pdm config check_update false
    post_install:
      - pdm sync --no-self --dev --group=doc
    pre_build:
      - python -m sphinx -b linkcheck docs/source/ $READTHEDOCS_OUTPUT/linkcheck

sphinx:
  configuration: docs/source/conf.py
