name: 'OpenBSD VM'
description: 'Install OpenBSD VM with python3, PDM and tox pre-installed'
inputs:
  python-version:
    description: "Version range or exact version of Python to use, using SemVer's version range syntax."
    required: true
  run:
    description: 'The CI command to run'
    required: true
  release:
    description: 'The release version of OpenBSD vm'
    required: false
  envs:
    description: 'The envs to pass into OpenBSD vm'
    required: false
  sync:
    description: 'How to synchronize the source code to/from the VM, Values can be:  rsync(default), and sshfs'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Load Python configuration
      uses: cardinalby/export-env-action@v2
      with:
        envFile: ${{ github.action_path }}/python/${{ inputs.python-version }}.conf
    - name: Run on VM
      uses: vmactions/openbsd-vm@v1
      with:
        release: ${{ inputs.release }}
        usesh: true
        envs: ${{ inputs.envs }}
        sync: ${{ inputs.sync }}
        prepare: |
          set -e
          command -v ${{ env.OPENBSD_PYTHON_BIN }}
          pkg_add -v git
        run: |
          set -e
          export PYTHON="${{ env.OPENBSD_PYTHON_BIN }}"
          $PYTHON -m venv --upgrade-deps /tmp/.venv
          . /tmp/.venv/bin/activate

          $PYTHON -m pip install -r .github/actions/requirements-tox.txt
          tox --version
          ${{ inputs.run }}
