name: Cleanup caches by a branch

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Run on pull request number'
        required: false
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        run: |
          REPO=${{ github.repository }}
          BRANCH=${{ env.PULL_REQUEST_NUMBER && format('refs/pull/{0}/merge', env.PULL_REQUEST_NUMBER) || github.ref }}

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          gh cache delete -R "$REPO" --all --ref "$BRANCH" --succeed-on-no-caches
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number || inputs.pull_request_number }}
