# This action requires that any PR targeting the main branch should add a
# changelog fragment file in the changelog.d/ directory. If a changelog entry
# is not required, add the "pr-skip-changelog" label to disable this action.

name: Changelog

on:
  pull_request:
    types:
      - opened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - reopened
      - labeled
      - unlabeled
    branches:
      - main

jobs:
  changelog:
    if: github.event.pull_request.draft != true && !contains(github.event.pull_request.labels.*.name, 'pr-skip-changelog')
    runs-on: ubuntu-latest

    name: Check changelog
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup tox
        uses: ./.github/actions/setup-tox
        with:
          python-version: '3.12'
      - name: Check for changelog fragment
        run: tox run -e towncrier_check -- --compare-with origin/${{ github.base_ref }}
