name: Lint

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - converted_to_draft
      - ready_for_review
    branches:
      - main
    paths:
      - 'benchmark_server/**.py'
      - 'docs/**.py'
      - 'micro_benchmarks/**.py'
      - 'src/**.pyi?'
      - 'tests/**.pyi?'
      - 'tox.ini'
      - 'pyproject.toml'
      - 'pdm.lock'
      - '.github/actions/setup-tox/**'
      - '.github/workflows/lint.yml'
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - 'benchmark_server/**.py'
      - 'docs/**.py'
      - 'micro_benchmarks/**.py'
      - 'src/**.pyi?'
      - 'tests/**.pyi?'
      - 'tox.ini'
      - 'pyproject.toml'
      - 'pdm.lock'
      - '.github/actions/setup-tox/**'
      - '.github/workflows/lint.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  type-hinting:
    if: |
      (github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:'))
      && (github.event_name != 'pull_request' || github.event.pull_request.draft != true)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup tox
        uses: ./.github/actions/setup-tox
        with:
          python-version: '3.11'
      - name: Launch checks
        run: tox run -f mypy
