name: Release a version

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build sdist/wheel
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    name: Distribute packages
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v4
        with:
          name: easynetwork-dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  build-failure:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Delete release
        run: gh release delete ${{ github.ref_name }} --yes --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
