name: Release a version

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build sdist/wheel
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: easynetwork-dist

  release:
    needs: build
    runs-on: ubuntu-latest

    name: Distribute packages
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v3
        with:
          name: easynetwork-dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.7.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  build-failure:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Delete release
        run: gh release delete ${{ github.ref_name }} --yes --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
